import numpy as np

var=np.zeros((2,3,3),dtype=int)
print("Zero wala array ",var)
 # this zero methode create a array with the numbers zera
print()
a=np.arange(2,60,7) 
# this functin return a array between 2 and 60 with the step 2 means it will add 2 to its previous element 
print("the array generatedd by the arrange function",a)
print()
line=np.linspace(0,100,8,dtype=int) # this methode generate an array in a given range with the given number of element by default it generate a floating number array 
# line=np.linspace(0,3,5)
print("the array generated by linespace",line)
print()

full=np.full((3,4,2),7) # this full methode of np generate a array with the given number i.e 7 in this case
print("the array generated by the full methode is :",full)
print()
eye=np.eye(3, dtype=int)
print("the eye methode output",eye) # this methode return a identity metrix 
print()
# print(full)
# var1=np.ones([])
var3=np.random.rand(3,3,3)
var4=np.random.rand(3)
print("the random array is :",np.round(var3*100))
print("the random array is :",np.round(var4*100))
# var3=np.absolute(var3)
# print(var)
# print(var1)
# print(var3)

var5=np.empty((2,2), dtype=int)
print("the empty array :", var5)
print()
print("shape of the array :",full.shape)
print("length of the array : ",len(full))
print("size of the array :",full.size)
print(full.dtype.name)
print(full.astype(float))
print(full.dtype.name)
print("shape of [1,2,3,4]",np.array([1,2,3,4]).shape)
